### ISSUE TITLE
Log parser get's stuck on erroneous input

### ISSUE THREAD

**Issue by ajasja** [radakb/pynamd#2]
Hi!

I tried to read a malformed log (by mistake:). The parser gets stuck in an infinite loop.

Here is the code:

```
import pynamd as nd
l = nd.NamdLog("00002-err.log")
```

[00002-err.zip](https://github.com/radakb/pynamd/files/660728/00002-err.zip)

**Comment by ajasja** [comment]
00002-err.log:
Restartfiles for out/11-run-wat/00001 don't exist!
Restartfiles for out/11-run-wat/00001 don't exist!
Restartfiles for out/11-run-wat/00001 don't exist!
Restartfiles for out/11-run-wat/00001 don't exist!
Restartfiles for out/11-run-wat/00001 don't exist!
Restartfiles for out/11-run-wat/00001 don't exist!
Restartfiles for out/11-run-wat/00001 don't exist!

**Comment by radakb** [comment]
I'm not surprised/knew this was an issue. The code for reading the "Info:" headers is very simple minded (border line irresponsible) and doesn't know what to do if there aren't any info lines. Does adding the keyword "info = None" remove the error?

**Comment by ajasja** [comment]
That's the problem: there is no error, it just loops forever, which is the
worst possible response:)

**Comment by ajasja** [comment]
I think here is the problem
https://github.com/radakb/pynamd/blob/master/pynamd/log.py#L425
And this loop should also check for the end of the file. I can do a pull
request if you like.

Best,
Ajasja

**Comment by radakb** [comment]
By all means. You're right, a simple end of file check should fix the problem.

**Comment by ajasja** [comment]
It's here
https://github.com/radakb/pynamd/pull/3
I just removed the whole skip ahead (since there is an ` if line.startswith(INFO):` later on anyway.

Everything should work (although adding some unit tests is a good idea as well).

**Comment by ajasja** [comment]
Resolved by https://github.com/radakb/pynamd/pull/3
